name: Tests and Linter
on: [push]
jobs:
  container-job:
      name: Tests
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres
          env:
            POSTGRES_PASSWORD: admin
            POSTGRES_DBNAME: postgres
            POSTGRES_USER: viktoria
            POSTGRES_PORT: 2206
            POSTGRES_HOST: 127.0.0.1
          ports:
          - 2206:5432
      steps:
      - uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.4"
      - name: Dependencies install and test api
        env:
            POSTGRES_PASSWORD: admin
            POSTGRES_DBNAME: postgres
            POSTGRES_USER: viktoria
            POSTGRES_PORT: 2206
            POSTGRES_HOST: 127.0.0.1
            FLASK_PORT: 5000
        run: |
          PGPASSWORD=admin psql -h 127.0.0.1 -p 2206 -d postgres -U viktoria  
          python3 -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          python3 -m pip install pytest
          pip install gunicorn
          python3 -m gunicorn --bind=127.0.0.1:${FLASK_PORT} app:app -w=4 --daemon
          ping 127.0.0.1
          pytest test.py
      - name: Dependencies install and test webapp
        env:
            POSTGRES_PASSWORD: admin
            POSTGRES_DBNAME: postgres
            POSTGRES_USER: viktoria
            POSTGRES_PORT: 2206
            POSTGRES_HOST: 127.0.0.1
            FLASK_PORT: 5001
        run: |
          python3 -m gunicorn --bind=127.0.0.1:${FLASK_PORT} app:app -w=4 --daemon
          pytest test.py
          
  linter_api_and_tests:
    name: linter api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        python -m pip install wemake-python-styleguide
    - name: Lint with flake8
      run: |
        flake8 

  linter_web:
    name: linter webapp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        python -m pip install wemake-python-styleguide
    - name: Lint with flake8
      run: |
        cd webapp
        flake8 app.py
        flake8 config.py
        flake8 test.py
